nelmio_cors:
    defaults:
        allow_origin: [ '*' ]
        allow_headers: [ '*' ]
        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH' ]
        max_age: 3600
        hosts: [ ]
        origin_regex: false
    paths:
        '^/': null
