services:
    php:
        build:
            context: .
            dockerfile: ./.server/docker/Dockerfile
        volumes:
            - ./:/app
            #- ./vendor:/app/vendor
            #- ./var:/app/var
        working_dir: /app
        user: 1000:1000
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            app-network:
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        image: nginx:alpine
        ports:
            - "8088:80"
        volumes:
            - ./:/app
            - ./.server/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            app-network:
        extra_hosts:
            - "host.docker.internal:host-gateway"
    postgres:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        ports:
            - "127.0.0.2:5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
        healthcheck:
          test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-postgres}", "-U", "${POSTGRES_USER:-postgres}"]
          timeout: 5s
          retries: 5
          start_period: 60s
        volumes:
          - database_data:/var/lib/postgresql/data:rw
        networks:
            app-network:

networks:
    app-network:
        #driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
